[agent-control]feat: add helm test (NR-441527) (#1903)
Adds a helm test in order to easy the troubleshooting whenever the
installation fails.

The goal to add this command concatenated with the install command
proviede by the jumpstart in the way like `helm upgrade --install
agent-control .... || helm test agent-control ...`, so whenever the
installation fails , this test will run and print the logs into the cli.

This is an example 

``` shell
$ helm upgrade --install agent-control -n newrelic-agent-control charts/agent-control --create-namespace --values values.yaml || helm test agent-control --logs -n newrelic-agent-control

Release "agent-control" does not exist. Installing it now.
Error: failed post-install: 1 error occurred:
	* job agent-control-install-job failed: BackoffLimitExceeded


NAME: agent-control
LAST DEPLOYED: Fri Aug 29 14:58:17 2025
NAMESPACE: newrelic-agent-control
STATUS: failed
REVISION: 1
TEST SUITE:     agent-control-helm-test
Last Started:   Fri Aug 29 14:59:05 2025
Last Completed: Fri Aug 29 14:59:09 2025
Phase:          Succeeded

POD LOGS: agent-control-helm-test
[pod/agent-control-install-job-l7mnf/install-agent-control] Creating agent-control-deployment resources owned by Agent Control...
[pod/agent-control-install-job-l7mnf/install-agent-control] 2025-08-29T12:59:02 DEBUG tracing_subscriber initialized successfully
[pod/agent-control-install-job-l7mnf/install-agent-control] 2025-08-29T12:59:02 DEBUG Installing default rustls crypto provider
[pod/agent-control-install-job-l7mnf/install-agent-control] 2025-08-29T12:59:02  INFO Installing release agent-control-deployment
[pod/agent-control-install-job-l7mnf/install-agent-control] 2025-08-29T12:59:02 DEBUG Starting the runtime
[pod/agent-control-install-job-l7mnf/install-agent-control] 2025-08-29T12:59:02 DEBUG Starting the k8s client
[pod/agent-control-install-job-l7mnf/install-agent-control] 2025-08-29T12:59:02 DEBUG trying inClusterConfig for k8s client
[pod/agent-control-install-job-l7mnf/install-agent-control] 2025-08-29T12:59:02 DEBUG k8s client initialization succeeded
[pod/agent-control-install-job-l7mnf/install-agent-control] 2025-08-29T12:59:02 DEBUG Initializing dynamic object manager for type: TypeMetaNamespaced { type_meta: TypeMeta { api_version: "helm.toolkit.fluxcd.io/v2", kind: "HelmRelease" }, namespace: "newrelic-agent-control" }
[pod/agent-control-install-job-l7mnf/install-agent-control] 2025-08-29T12:59:02 ERROR Operation failed: failed to apply resource: could not get helmRelease with name agent-control-deployment: api resource kind not present in the cluster: apiVersion: helm.toolkit.fluxcd.io/v2 kind: HelmRelease
[pod/agent-control-install-job-q92pb/install-agent-control] Creating agent-control-deployment resources owned by Agent Control...
[pod/agent-control-install-job-q92pb/install-agent-control] 2025-08-29T12:58:42 DEBUG tracing_subscriber initialized successfully
[pod/agent-control-install-job-q92pb/install-agent-control] 2025-08-29T12:58:42 DEBUG Installing default rustls crypto provider
[pod/agent-control-install-job-q92pb/install-agent-control] 2025-08-29T12:58:42  INFO Installing release agent-control-deployment
[pod/agent-control-install-job-q92pb/install-agent-control] 2025-08-29T12:58:42 DEBUG Starting the runtime
[pod/agent-control-install-job-q92pb/install-agent-control] 2025-08-29T12:58:42 DEBUG Starting the k8s client
[pod/agent-control-install-job-q92pb/install-agent-control] 2025-08-29T12:58:42 DEBUG trying inClusterConfig for k8s client
[pod/agent-control-install-job-q92pb/install-agent-control] 2025-08-29T12:58:42 DEBUG k8s client initialization succeeded
[pod/agent-control-install-job-q92pb/install-agent-control] 2025-08-29T12:58:42 DEBUG Initializing dynamic object manager for type: TypeMetaNamespaced { type_meta: TypeMeta { api_version: "helm.toolkit.fluxcd.io/v2", kind: "HelmRelease" }, namespace: "newrelic-agent-control" }
[pod/agent-control-install-job-q92pb/install-agent-control] 2025-08-29T12:58:42 ERROR Operation failed: failed to apply resource: could not get helmRelease with name agent-control-deployment: api resource kind not present in the cluster: apiVersion: helm.toolkit.fluxcd.io/v2 kind: HelmRelease
[pod/agent-control-install-job-w28wp/install-agent-control] Creating agent-control-deployment resources owned by Agent Control...
[pod/agent-control-install-job-w28wp/install-agent-control] 2025-08-29T12:58:32 DEBUG tracing_subscriber initialized successfully
[pod/agent-control-install-job-w28wp/install-agent-control] 2025-08-29T12:58:32 DEBUG Installing default rustls crypto provider
[pod/agent-control-install-job-w28wp/install-agent-control] 2025-08-29T12:58:32  INFO Installing release agent-control-deployment
[pod/agent-control-install-job-w28wp/install-agent-control] 2025-08-29T12:58:32 DEBUG Starting the runtime
[pod/agent-control-install-job-w28wp/install-agent-control] 2025-08-29T12:58:32 DEBUG Starting the k8s client
[pod/agent-control-install-job-w28wp/install-agent-control] 2025-08-29T12:58:32 DEBUG trying inClusterConfig for k8s client
[pod/agent-control-install-job-w28wp/install-agent-control] 2025-08-29T12:58:32 DEBUG k8s client initialization succeeded
[pod/agent-control-install-job-w28wp/install-agent-control] 2025-08-29T12:58:32 DEBUG Initializing dynamic object manager for type: TypeMetaNamespaced { type_meta: TypeMeta { api_version: "helm.toolkit.fluxcd.io/v2", kind: "HelmRelease" }, namespace: "newrelic-agent-control" }
[pod/agent-control-install-job-w28wp/install-agent-control] 2025-08-29T12:58:32 ERROR Operation failed: failed to apply resource: could not get helmRelease with name agent-control-deployment: api resource kind not present in the cluster: apiVersion: helm.toolkit.fluxcd.io/v2 kind: HelmRelease
```