[agent-control-bootstrap] exit on cli error (#1950)
#### Is this a new chart

no

#### What this PR does / why we need it:

Fail fast when `agent-control-cd` can't be installed because of a wrong
version.

```
error: the server doesn't have a resource type "HelmRelease"                                                                                                                                │
│ Adding agent-control-cd repository...                                                                                                                                                       │
│ "newrelic-agent-control-cd" has been added to your repositories                                                                                                                             │
│ Installing agent-control-cd...                                                                                                                                                              │
│ Release "agent-control-cd" does not exist. Installing it now.                                                                                                                               │
│ Error: chart "agent-control-cd" matching 10.0.0 not found in newrelic-agent-control-cd index. (try 'helm repo update'): no chart version found for agent-control-cd-10.0.0                  │
│ Creating agent-control-cd resources owned by Agent Control...                                                                                                                               │
│ {"timestamp":"2025-09-30T13:11:03","level":"DEBUG","message":"tracing_subscriber initialized successfully"}                                                                                 │
│ {"timestamp":"2025-09-30T13:11:03","level":"DEBUG","message":"Installing default rustls crypto provider"}                                                                                   │
│ {"timestamp":"2025-09-30T13:11:03","level":"INFO","message":"Installing release agent-control-cd"}                                                                                          │
│ {"timestamp":"2025-09-30T13:11:03","level":"DEBUG","message":"Starting the runtime"}                                                                                                        │
│ {"timestamp":"2025-09-30T13:11:03","level":"DEBUG","message":"Starting the k8s client"}                                                                                                     │
│ {"timestamp":"2025-09-30T13:11:03","level":"DEBUG","message":"trying inClusterConfig for k8s client"}                                                                                       │
│ {"timestamp":"2025-09-30T13:11:03","level":"DEBUG","message":"k8s client initialization succeeded"}                                                                                         │
│ {"timestamp":"2025-09-30T13:11:03","level":"DEBUG","message":"Initializing dynamic object manager for type: TypeMetaNamespaced { type_meta: TypeMeta { api_version: \"helm.toolkit.fluxcd.i │
│ {"timestamp":"2025-09-30T13:11:03","level":"ERROR","message":"Operation failed: failed to apply resource: could not get helmRelease with name agent-control-cd: api resource kind not prese │
│ Failed to create agent-control-cd resources owned by Agent Control.
```

#### Which issue this PR fixes

  - fixes #NR-464888

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove
unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)